server:
  port: 9192

spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/lakeside_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true

  servlet:
    multipart:
      max-file-size: 10MB  # Dosya boyutunu art?rd?m
      max-request-size: 10MB # Yükleme s?n?r?n? dosya boyutuna göre art?rd?m
